name: meiosis-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-wasm-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true
          
      - name: Build WebAssembly Wheel
        run: pixi run build-wasm

      - name: Generate Forced 4_0_9 Tag
        run: |
          cd dist
          WHEEL=$(ls *.whl | grep "pyemscripten" | head -n 1)
          if [ -n "$WHEEL" ]; then
            FORCED_WHEEL=$(echo $WHEEL | sed 's/pyemscripten_[0-9]\{4\}_[0-9]/emscripten_4_0_9/')
            cp "$WHEEL" "$FORCED_WHEEL"
          fi
        
      - name: Store Wasm artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-wasm32-release
          path: ./dist/*.whl

  publish-release:
    needs: [build-wasm-wheel]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Wasm wheels
        uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-wasm32-release
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          generate_release_notes: true